name: ExteriorPowersCategories
version: "2021.11-02"
license: "GPL-2.0-or-later"
date: 2021-11-13
description: |
    The graded category of exterior powers of objects of a given Ab-category

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2019.10.29"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "CategoryConstructor"
      version: ">=2021.04-01"
      url: "https://homalg-project.github.io/pkg/CategoryConstructor"

www: https://homalg-project.github.io/pkg/ExteriorPowersCategories
readme: README.md
packageinfo: https://homalg-project.github.io/ExteriorPowersCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ExteriorPowersCategories/releases/download/v2021.11-02/ExteriorPowersCategories-2021.11-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/ExteriorPowersCategories/releases/download/v2021.11-02/ExteriorPowersCategories-2021.11-02.zip

pdf: https://github.com/homalg-project/ExteriorPowersCategories/releases/download/v2021.11-02/ExteriorPowersCategories-2021.11-02.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Exterior power categories.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar21</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>ExteriorPowersCategories, The graded category of exterior powers of objects of a given Ab-category,
             Version 2021.11-02</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/ExteriorPowersCategories">https://homalg-project.github.io/pkg/ExteriorPowersCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ ExteriorPowersCategories2021.11-02,
      author =           {Barakat, M.},
      title =            {{ExteriorPowersCategories},  The  graded  category  of
                          exterior  powers  of  objects  of a given Ab-category,
                          {V}ersion 2021.11-02},
      month =            {Nov},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/ExteriorPowersCategories}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{ExteriorPowersCategories}}},
      keywords =         {Exterior power categories},
      printedkey =       {Bar21}
    }

